# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch
torch.__version__
!nvidia-smi

# Create random tensor
random_tensor_1 = torch.rand(7, 7)
random_tensor_1

Fri Aug 18 13:43:09 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8    14W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

tensor([[0.2461, 0.1505, 0.6923, 0.7065, 0.1506, 0.7232, 0.8877],
        [0.1011, 0.7291, 0.1099, 0.8489, 0.4752, 0.9341, 0.3590],
        [0.1829, 0.9595, 0.5562, 0.0333, 0.6010, 0.6836, 0.2365],
        [0.3872, 0.9362, 0.4219, 0.4532, 0.3178, 0.9352, 0.5122],
        [0.1272, 0.5805, 0.2763, 0.9942, 0.3771, 0.3799, 0.9521],
        [0.4291, 0.7915, 0.5073, 0.0115, 0.6069, 0.9853, 0.3053],
        [0.6391, 0.8621, 0.4431, 0.2062, 0.4717, 0.7990, 0.2884]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication
multiplication = torch.mm(random_tensor_1, random_tensor_2.T) # transposed the 2nd
multiplication

tensor([[2.2252],
        [1.5010],
        [1.2843],
        [1.7425],
        [2.0973],
        [1.4603],
        [1.5542]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t1 = torch.rand(7, 7)
t2 = torch.rand(1, 7) # .T to transpose so that inner dimensions match
print(f"Original shapes: t1 = {t1.shape}, t2 = {t2.shape}")
print(f"T2 shape after transposing: {t2.T.shape}")
print(f"Multiplying: {t1.shape} @ {t2.T.shape} <- Inner dimensions must match")

# Matrix multiply tensors
mult = torch.matmul(t1, t2.T)
print(f"Result of t1 @ t2.T: {mult}")
print(f"Output shape: {mult.shape}")

Original shapes: t1 = torch.Size([7, 7]), t2 = torch.Size([1, 7])
T2 shape after transposing: torch.Size([7, 1])
Multiplying: torch.Size([7, 7]) @ torch.Size([7, 1]) <- Inner dimensions must match
Result of t1 @ t2.T: tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
Output shape: torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

# Create two random tensors on GPU
tensor_A = torch.rand(2,3).to(device) # use to(device) here and not device=cuda!!!
tensor_B = torch.rand(2,3).to(device)

print(tensor_A, tensor_B)

Using device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
output = torch.mm(tensor_A, tensor_B.T)

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max = torch.max(output)
print(f"Max value from the resulting tensor: {max}")

# Find min
min = torch.min(output)
print(f"Min value from the resulting tensor: {min}")

Max value from the resulting tensor: 0.5617256760597229
Min value from the resulting tensor: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
argmax = torch.argmax(output)
print(f"Position of max value (argmax) from the resulting tensor: {argmax}")

# Find arg min
argmin = torch.argmin(output)
print(f"Position of min value (argmin) from the resulting tensor: {argmin}")

Position of max value (argmax) from the resulting tensor: 3
Position of min value (argmin) from the resulting tensor: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
randomtensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
randomtensor_without_single_dims = torch.squeeze(randomtensor)

# Print out tensors and their shapes
print(randomtensor)
print(f"Shape of randomtensor: {randomtensor.shape}")
print(randomtensor_without_single_dims)
print(f"Shape of randomtensor_without_single_dims: {randomtensor_without_single_dims.shape}")


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of randomtensor: torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of randomtensor_without_single_dims: torch.Size([10])
